{
 "title": "Snackdrawer Golden Signals",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_requests_bucket[5m])) by (le))",
     "legendFormat": "p95 API latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_requests_bucket[5m])) by (le))",
     "legendFormat": "p95 DB latency"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_api_requests", "legendFormat": "Active API requests" },
    { "expr": "active_db_queries", "legendFormat": "Active DB queries" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Number of requests or queries per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_requests_count{job=\"snackdrawer\"}[1m]))",
     "legendFormat": "API Requests"
    },
    {
     "expr": "sum(rate(db_requests_count{job=\"snackdrawer\"}[1m]))",
     "legendFormat": "DB Queries"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(request_error_count[5m])/sum(rate(api_requests_count{job=\"snackdrawer\"}[5m]))",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}