{
 "title": "Snackdrawer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "p95 /auth",
   "type": "graph",
   "description": "P95 response times for queries to the /auth endpoints",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_requests_bucket{endpoint=~\"/auth/.*\"}[5m])) by (le, endpoint, method))"
    }
   ]
  },
  {
   "title": "p95 /snacks",
   "type": "graph",
   "description": "P95 response times for the /snacks endpoints",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_requests_bucket{endpoint=~\"/snacks/.*\"}[5m])) by (le, method, endpoint))"
    }
   ]
  },
  {
   "title": "p95 /drawers",
   "type": "graph",
   "description": "P95 response times for the /drawers endpoints",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(api_requests_bucket{endpoint=~\"/drawers/.*\"}[5m])) by (le,endpoint,method))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  }
 ]
}